#!/bin/bash
# Quick reference for Xenober16 transpiler commands

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         Xenober16 Transpiler - Quick Reference                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📝 INTERPRET (run directly):"
echo "   raku -I lib xen16.raku test-files/test-14-comprehensive-2.xen"
echo ""
echo "🔄 TRANSPILE TO PROG8:"
echo "   raku -I lib xen16.raku --transpile=prog8 input.xen"
echo "   raku transpile-prog8.raku input.xen output.p8"
echo ""
echo "🧪 RUN TESTS:"
echo "   raku test-transpiler.raku                    # Run all tests"
echo "   raku test-transpiler.raku --verbose          # Show diffs"
echo "   raku test-transpiler.raku --only=FOR         # Specific test"
echo "   raku test-transpiler.raku --update           # Update expected"
echo ""
echo "📚 DOCUMENTATION:"
echo "   cat TRANSPILER-EXAMPLES.md                   # Examples"
echo "   cat test-files/TRANSPILER-TESTS.md           # Test docs"
echo "   cat README.md                                # Language spec"
echo ""
echo "📁 FILES:"
echo "   lib/Xenober16/Prog8Transpiler.rakumod        # Transpiler"
echo "   test-files/*.xen                             # Test inputs"
echo "   test-files/expected-p8/*.p8                  # Expected outputs"
echo ""
echo "✨ EXAMPLES:"
echo "   # Create a new Xenober16 file and transpile it"
echo "   cat > myprogram.xen << 'EOF'"
echo "   MODULE IDENTIFICATION DIVISION."
echo "       MODULE-ID. MyProgram."
echo "   "
echo "   DATA DIVISION."
echo "       x: uint8;"
echo "   "
echo "   MAIN DIVISION."
echo "       x := 42;"
echo "       SAY \"Hello from Xenober16!\";"
echo "       SAY x;"
echo "   "
echo "   MODULE END."
echo "   EOF"
echo ""
echo "   raku transpile-prog8.raku myprogram.xen myprogram.p8"
echo ""
